name: Sync + Build + Publish

on:
  schedule: 
  - cron: "*/5 * * * *"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: openai/openai-node
        source_branch: main
        destination_branch: sync
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      with:
        source_branch: sync
        destination_branch: main
